# Generated by Django 3.1.6 on 2021-02-20 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketcomment',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='issue_tracker.ticket'),
        ),
        migrations.AlterField(
            model_name='ticketcomment',
            name='comment_text',
            field=models.TextField(),
        ),
    ]
