# Generated by Django 3.1.6 on 2021-02-20 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracker', '0002_auto_20210220_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketcomment',
            name='comment_text',
            field=models.CharField(max_length=550),
        ),
    ]
