# Generated by Django 3.1.6 on 2021-02-20 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracker', '0003_auto_20210220_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_choice',
            field=models.CharField(choices=[('Bug', 'Bug'), ('Enhancement', 'Enhancement'), ('New_Feature', 'New Feature')], default='Bug', max_length=20),
        ),
    ]
