# Generated by Django 3.1.6 on 2021-02-22 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracker', '0004_auto_20210220_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminticket',
            name='additional_comments',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
    ]
